//Do not edit this file

waitUntil {uiSleep 3; !isNil "A3EAI_locations_ready"};

call compile preprocessFileLineNumbers format ["%1\A3EAI_custom_defs.sqf",A3EAI_installedFolder];

A3EAI_customSpawnsReady = true;
